### ISSUE TITLE
How to establish @IBOutlet collectionView in Swift?

### ISSUE THREAD

**Issue by orkenstein** [DenHeadless/DTCollectionViewManager#10]
In order to use  `DTCollectionViewManager` i'm trying to implement desired functionality in my `DTCollectionViewController` sub-class. However, I can not add `@IBOutlet` for `collectionView`.
What is best practice?
The following code:
            ``@IBOutlet var collectionView: UICollectionView!``

gives me compiler error:
```
Property 'collectionView' with type 'UICollectionView!' cannot override a property with type           'UICollectionView'
Setter for 'collectionView' with Objective-C selector 'setCollectionView:' conflicts with setter for       'collectionView' from superclass 'DTCollectionViewController' with the same Objective-C selector
```

**Comment by DenHeadless** [comment]
Just link your UICollectionView to DTCollectionViewController, you don't need to override collectionView property in your subclass.
